// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission07_twoodru8.Models;

namespace Mission07_twoodru8.Migrations
{
    [DbContext(typeof(MovieFormDBContext))]
    [Migration("20230220174505_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Mission07_twoodru8.Models.Categories", b =>
                {
                    b.Property<int>("CategoriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriesId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoriesId = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoriesId = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoriesId = 3,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoriesId = 4,
                            CategoryName = "Scary"
                        });
                });

            modelBuilder.Entity("Mission07_twoodru8.Models.MovieFormModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 100,
                            CategoriesId = 1,
                            Director = "George Lucas",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Star Wars: Episode III",
                            Year = 2005
                        },
                        new
                        {
                            MovieId = 101,
                            CategoriesId = 1,
                            Director = "George Lucas",
                            Edited = false,
                            Rating = "PG",
                            Title = "Star Wars: Episode II",
                            Year = 2002
                        },
                        new
                        {
                            MovieId = 102,
                            CategoriesId = 1,
                            Director = "George Lucas",
                            Edited = false,
                            Rating = "PG",
                            Title = "Star Wars: Episode I",
                            Year = 1999
                        });
                });

            modelBuilder.Entity("Mission07_twoodru8.Models.MovieFormModel", b =>
                {
                    b.HasOne("Mission07_twoodru8.Models.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
